version: '2'

services:

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootp
    ports:
      - 3306:3306
    volumes:
      - "./scripts/db:/docker-entrypoint-initdb.d"

  wiremock:
    image: "rodolpheche/wiremock"
    ports:
      - 9080:8080
    volumes:
      - "./scripts/wiremock:/home/wiremock/mappings"

  moveon:    
    image: "veon/moveon:latest"
    environment:
      - MOVEON_DB_HOST=mysql
      - MOVEON_DB_USER=root
      - MOVEON_DB_PASS=rootp
      - MOVEON_ALLOC_HOST=wiremock
      - MOVEON_ALLOC_PORT=8080
    ports:
      - 8080:8080
